{
 "title": "Karakoram Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Recorded Temperatures in C",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature C",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overwatch",
     "query": "SELECT distinct(\"temperature_c\") FROM \"overwatch\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Temperature F",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "fahrenheit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "overwatch",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Temperature C",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "overwatch",
     "query": "SELECT \"temperature_c\" FROM \"autogen\".\"overwatch\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Average Temperature in C",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 3 },
   "targets": [
    {
     "alias": "Mean C Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overwatch",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mean Average Temperature in F",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "alias": "Mean F Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "overwatch",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}