{
 "title": "Theia Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Recorded Temperatures in C",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature C",
     "measurement": "theia",
     "query": "SELECT \"temperature_c\" FROM \"overwatch\"",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Temp F",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "fahrenheit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "theia",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Temp C",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "measurement": "theia",
     "query": "SELECT \"temperature_c\" FROM \"autogen\".\"overwatch\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Community Temperature in C",
   "type": "bargauge",
   "description": "Mean temperature of the entire community, in Celcius. ",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Mean C Temperature",
     "measurement": "theia",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Community Temperature in F",
   "type": "bargauge",
   "description": "The mean temperature of the entire community in Fahrenheit. ",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Mean F Temperature",
     "measurement": "theia",
     "select": [
      [
       { "params": [ "temperature_f" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "theia",
     "select": [
      [
       { "params": [ "temperature_c" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}